"""
Tests of the YamboInput class on input files generated by yambo (Lumen 2.1) for bulk silicon
(folder tests/data/yambo_inputs).
"""
import os, glob
import pytest
from mppi import InputFiles as I
from mppi.InputFiles.YamboInput import format_variable

DATA = os.path.join(os.path.dirname(os.path.abspath(__file__)),'data','yambo_inputs')
FILES = sorted(os.path.basename(f) for f in glob.glob(os.path.join(DATA,'*.in')))

def read(filename):
    return I.YamboInput(folder=DATA,filename=filename)

@pytest.mark.parametrize('filename',FILES)
def test_roundtrip(filename, tmp_path):
    # parse -> write -> parse gives the same arguments and variables
    inp = read(filename)
    inp.write(str(tmp_path),filename)
    inp2 = I.YamboInput(folder=str(tmp_path),filename=filename)
    assert inp2['arguments'] == inp['arguments']
    assert inp2['variables'] == inp['variables']

def test_runlevels():
    assert read('gw_ppa.in')['arguments'] == ['ppa','gw0','el_el_corr','dyson','HF_and_locXC','em1d']
    assert read('bse_diago.in')['arguments'] == ['optics','bss','bse','dipoles']
    assert read('rim_hf_all.in')['arguments'] == ['rim_cut','HF_and_locXC','infver']
    assert read('ypp_bands.in')['arguments'] == ['electrons','bnds']
    # the flags commented in the file (e.g. #RmTimeRev) are not active
    assert 'RmTimeRev' not in read('ypp_fixsyms.in')['arguments']

def test_variables():
    var = read('bse_diago.in')['variables']
    assert var['Nelectro'] == [8.0,'']
    assert var['BoseTemp'] == [-1.0,'eV']
    assert var['OccTresh'] == [1e-5,'']
    assert var['BSENGexx'] == [5985,'RL']
    assert var['DipApproach'] == 'G-space v'   # string with spaces and punctuation
    assert var['DipComputed'] == ''            # empty string
    assert var['KfnQP_Z'] == [complex(1.,0.),'']
    assert var['DrudeWBS'] == [complex(0.,0.),'eV']
    assert var['BSEBands'] == [[1,8],'']
    assert var['BSEEhEny'] == [[-1.0,-1.0],'eV'] # negative numbers in an array, units in the row
    var = read('ypp_bands.in')['variables']
    assert var['BANDS_kpts'] == [[],'']           # empty array

def test_hf_qpkrange():
    inp = read('hf.in')
    assert inp['arguments'][0] == 'HF_and_locXC'
    assert inp['variables']['QPkrange'] == [[1,32,1,8],'']
    inp.set_kRange(1,1)
    inp.set_bandRange(4,5)
    assert inp['variables']['QPkrange'] == [[1,1,4,5],'']

def test_format_variable():
    assert format_variable('DipApproach','G-space v') == 'DipApproach= "G-space v"'
    assert format_variable('EXXRLvcs',[30.,'Ha']) == 'EXXRLvcs= 30.0 Ha'
    assert format_variable('KfnQP_Z',[complex(1,0),'']) == 'KfnQP_Z= ( 1.0 , 0.0 )'
    assert format_variable('QPkrange',[[1,32,1,8],'']) == '% QPkrange\n1 | 32 | 1 | 8 |\n%'
    assert format_variable('BEnRange',[[0.,10.],'eV']) == '% BEnRange\n0.0 | 10.0 | eV\n%'
    assert format_variable('BANDS_kpts',[[[0.,0.,0.],[0.5,0.,0.]],'']) == \
        '% BANDS_kpts\n0.0 | 0.0 | 0.0 |\n0.5 | 0.0 | 0.0 |\n%'
    assert format_variable('BANDS_kpts',[[],'']) == '% BANDS_kpts\n%'
